services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Password
      - MYSQL_DATABASE=saleSysDB
    volumes:
      - todo-mysql-data:/var/lib/mysql

volumes:
  todo-mysql-data: